### PR TITLE
Separated the reporting of the API versions (#170)

### PR DESCRIPTION
**Pull request by matt-wills**
The changes in this PR mean the read/write API and client registration API can be specified separately when going to https://as.aspsp.$DOMAIN/oauth2/.well-known/openid-configuration

### CODE REVIEW

**Comment by BohoCode** [comment]
Deployment tests will need to be changed to expect 3.1.4 now in the deployment-specifications.

**Comment by BohoCode** [comment]
I had a PR for that didn't I??

**Comment by matt-wills** [comment]
> I had a PR for that didn't I??

Yes, I've replaced it with this one: https://github.com/ForgeCloud/ob-deploy/pull/569

(because the name of your branch had 3.1.4 in it!)

**Comment by BohoCode** [comment]
Matt, which issue is this a PR for??

**Comment by matt-wills** [comment]
> @matt-wills , which issue is this a PR for??

This one: https://github.com/OpenBankingToolkit/openbanking-tpp/issues/170

(I try to remember to put the issue number in the title of my PRs)

**Comment by BohoCode** [comment]
When the PR is in another repository it's not so useful to just have the number of the PR you also need to know the repo, so a full link in the description is more useful I think?

> > @matt-wills , which issue is this a PR for??
> 
> This one: [OpenBankingToolkit/openbanking-tpp#170](https://github.com/OpenBankingToolkit/openbanking-tpp/issues/170)
> 
> (I try to remember to put the issue number in the title of my PRs)

**Comment by BohoCode** [comment]
openbanking-tpp seems a strange place for me to have created that issue. I have now rehomd it in aspsp, i.e. this repo. It is now at 
https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/232

**Pull request merged**
